Params:
  release_notify:
    githubUrl: https://api.github.com/repos/{owner}/{repo}/releases

module:
  hugoVersion:
    extended: false
    # needed for multi-line dicts and some other advanced features:
    min: "0.80.0"  
    max: "1.00.0"
