module:
  imports:
  - path: github.com/hugo-mods/release-notify
  - path: github.com/hugo-mods/icons # just an example here
  replacements:
  - github.com/hugo-mods/release-notify -> ../../.

Params:
  release_notify:
    modules:
      "github.com/hugo-mods/icons":
        type: "minor" # notify for any minor and major releases
      # It is possible to include any dependeny here that is listed in the go.mod file, even indirect ones:
      "github.com/FortAwesome/Font-Awesome":
        type: "any" # notify for any version upgrade
        partial: "notifiers/changelog.html" # can be any partial, if ommitted, will use "default-notifier"

caches:
  getjson:
    maxAge: 2h # mitigate GitHub rate-limiting